---
- name: Install Mastodon
  hosts: all
  gather_facts: false
  tasks:

    - name: Mise à jour du système (apt)
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Return motd to registered var
      command: apt install -y curl wget gnupg apt-transport-https lsb-release ca-certificates