---
- name: Download curl command - CentOS
  yum:
    name: curl
    state: latest

- name: Download node js
  shell: |
    curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
    yum install -y nodejs

- name: Install Postgresql packages
  shell: |
    dnf install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    dnf install postgesql12-server
    dnf --repo pgdg12 install postgresql12-server

- name: Install System Packages
  yum:
    name:
      - ImageMagick
    state: latest

- name: Install Remaining System Packages
  shell: |
    dnf install epel-release dnf-utils
    yum-config-manager --set-enabled PowerTools
    yum-config-manager --add-repo=https://negativo17.org/repos/epel-multimedia.repo
    dnf install ffmpeg

#    sudo yum install -y curl wget gnupg apt-transport-https lsb-release ca-certificates
#   curl -sL https://deb.nodesource.com/setup_16.x | bash -
#   wget -O /usr/share/keyrings/postgresql.asc https://www.postgresql.org/media/keys/ACCC4CF8.asc
#   echo "deb [signed-by=/usr/share/keyrings/postgresql.asc] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/postgresql.list