name: Install Mastodon
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: "44.193.28.39"
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: "22"
        script: whoami >> /home/ubuntu/test_file && cat /home/ubuntu/test_file 

    - name: Clone Repo & Run Ansible
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: "44.193.28.39"
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: "22"
        script: |
          rm -rf Install-Mastodon
          git clone https://github.com/tpanagoda/Install-Mastodon.git
          cd Install-Mastodon
          echo ${{ secrets.SSH_KEY }} > ansible-node.pem
          chmod 600 ansible-node.pem
          ansible-playbook install.yml