name: Install Mastodon
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: executing remote ssh commands using password
      uses: ./
      with:
        host: "44.193.28.39"
        username: "ubuntu"
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd ~
          mkdir new_folder 

    - name: set ansible config secrets
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir .ssh
        echo "Showing Secret Keys"
        echo ${{ secrets.SSH_KEY }}
        echo "$SSH_KEY" > .ssh/id_apitest
        chmod 600 .ssh/id_apitest
        ssh ubuntu@44.193.28.39
