name: Install Mastodon
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: executing remote ssh commands using password
      uses: ./
      with:
        host: "44.193.28.39"
        username: "ubuntu"
        password: ${{ secrets.SSH_KEY }}
        port: 22
        script: whoami
